name: Monitor Emas Logam Mulia

on:
  schedule:
    # SIANG (06:00–22:00 WIB) → tiap 3 menit
    - cron: "*/3 23-23 * * *"   # 06:00–06:59 WIB
    - cron: "*/3 0-15 * * *"    # 07:00–22:59 WIB

    # MALAM (22:00–06:00 WIB) → tiap 10 menit
    - cron: "*/10 16-22 * * *"  # 23:00–05:59 WIB

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests beautifulsoup4
      - run: python monitor.py
        env:
          FONNTE_TOKEN: ${{ secrets.FONNTE_TOKEN }}
